apiVersion: audit.k8s.io/v1beta1
kind: Policy
omitStages:
- RequestReceived
rules:
- level: None
  resources:
  - group: ''
    resources:
    - events
- level: None
  resources:
  - group: oauth.openshift.io
    resources:
    - oauthaccesstokens
    - oauthauthorizetokens
- level: None
  nonResourceURLs:
  - "/api*"
  - "/version"
  - "/healthz"
  - "/readyz"
  userGroups:
  - system:authenticated
  - system:unauthenticated
- level: Metadata
  omitStages:
  - RequestReceived
