apiVersion: v1
kind: Endpoints
metadata:
  name: openshift-oauth-apiserver
  namespace: default
subsets:
- addresses:
  - ip: {{ .OauthAPIClusterIP }}
  ports:
  - name: https
    port: 443
    protocol: TCP
