apiVersion: v1
kind: Service
metadata:
  name: openshift-oauth-apiserver
spec:
  clusterIP: {{ .OauthAPIClusterIP }}
  selector:
    app: openshift-oauth-apiserver
  ports:
  - name: https
    port: 443
    targetPort: 8443
